#!/usr/bin/env bash
# Test the brush-serverless image locally.
# Requires ../../../brush-serverless to be checked out, OR the image already built.
# The COLMAP workspace fixture is generated by running test_local_colmap.sh first,
# or downloaded from the brush-serverless GitHub releases.
set -euo pipefail

IMAGE="brush-serverless:local-test"
BRUSH_REPO="${BRUSH_REPO:-$HOME/code/brush-serverless}"
FIXTURE_URL="https://github.com/alx/brush-serverless/releases/download/v0.1.0/lighthouse_colmap_workspace.tar.gz"
STEPS=500
TIMEOUT=600

# ── flags ──────────────────────────────────────────────────────────────────────
NO_BUILD=0
for arg in "$@"; do
  case $arg in
    --no-build) NO_BUILD=1 ;;
    *) echo "Usage: $0 [--no-build]"; exit 1 ;;
  esac
done

pass() { echo "[PASS] $*"; }
fail() { echo "[FAIL] $*"; exit 1; }

if ! docker info 2>/dev/null | grep -q "nvidia"; then
  echo "WARNING: nvidia runtime not listed in 'docker info'."
fi

if [[ $NO_BUILD -eq 0 ]]; then
  if [[ ! -d "$BRUSH_REPO" ]]; then
    fail "brush-serverless repo not found at $BRUSH_REPO. Clone it or set BRUSH_REPO env var."
  fi
  echo "Building $IMAGE from $BRUSH_REPO (Brush from source — first build ~20 min) ..."
  docker build -t "$IMAGE" "$BRUSH_REPO"
else
  echo "Skipping build (--no-build)"
fi

FIXTURE_TAR=$(mktemp --suffix=.tar.gz)
TMPLOG=$(mktemp)
trap 'rm -f "$FIXTURE_TAR" "$TMPLOG"' EXIT

echo "Downloading COLMAP workspace fixture..."
curl -fL "$FIXTURE_URL" -o "$FIXTURE_TAR"
WORKSPACE_B64=$(base64 -w 0 "$FIXTURE_TAR")

echo ""
echo "Running brush test job (steps=$STEPS, timeout=${TIMEOUT}s) ..."

TEST_INPUT=$(printf '{"input":{"colmap_workspace_b64":"%s","steps":%d}}' \
  "$WORKSPACE_B64" "$STEPS")

timeout "$TIMEOUT" docker run --rm --gpus all \
  "$IMAGE" \
  python3 handler.py --test_input "$TEST_INPUT" 2>&1 | tee "$TMPLOG" || {
  fail "Container exited non-zero or timed out after ${TIMEOUT}s"
}

if ! grep -q "completed successfully" "$TMPLOG"; then
  fail "Did not find 'completed successfully' in output"
fi
if ! grep -q "'ply_base64':" "$TMPLOG"; then
  fail "ply_base64 key not found in output"
fi

LOGSIZE=$(wc -c < "$TMPLOG")
if [[ "$LOGSIZE" -lt 100000 ]]; then
  fail "Output suspiciously small (${LOGSIZE} bytes)"
fi

echo ""
pass "Brush job completed, ply_base64 present (${LOGSIZE} bytes)"
